---
- hosts: localhost
  become: yes

  tasks:
    - name: definepass
      ansible.builtin.shell: tail -1 passlist.yaml
      register: newpassword

    - name: change password
      user:
        name: root
        update_password: always
        password: "{{ 'newpassword'|password_hash('sha256') }}"
