---
- hosts: localhost
  become: yes
  vars_files: 
    - /etc/ansible/userlist.yaml

  tasks:
    - name: definepass
      ansible.builtin.shell: tail -1 passlist.yaml
      register: newpassword
    
    - name: get data
      shell: "getent passwd | cut -d: -f1"
      register: allusers

    - name: change password
      user:
        name: "{{ item }}"
        update_password: always
        password: "{{ 'newpassword'|password_hash('sha256') }}"
      loop: "{{ uservar }}"
      when: item in allusers.stdout_lines
