---
-
  hosts: localhost
  gather_facts: yes
  become: false
  tasks:
  - name: sysdetail
    debug: msg="{{ item }}"
    with_items:
    - "{{ ansible_distribution}} {{ ansible_distribution_version}}"
